### ISSUE TITLE
TROJAN

### ISSUE THREAD

**Issue by bzn2411** [Nyxonn/Discord-AIO#52]

**Comment by Nyxonn** [comment]
How can open-sourced project be a trojan?
Think about it before you post your stupid issue.

**Comment by jesse234** [comment]
hey bro your response just proved his suspicion, and hell ya trojans are always open source because you don't pay to get infected by malware its always free juicy stuff , well I know you meant to say that to script kiddies. if i must say this your code has a malicious behavior . oooooh fk i remember, this is github
